boot.o: boot.S multiboot.h x86_desc.h types.h
halt.o: halt.S
iret.o: iret.S
linker.o: linker.S
pit_link.o: pit_link.S
schedule_switch.o: schedule_switch.S
set_paging.o: set_paging.S
syscalls_handler.o: syscalls_handler.S
x86_desc.o: x86_desc.S x86_desc.h types.h
cursor.o: cursor.c cursor.h types.h i8259.h lib.h
file.o: file.c types.h file.h lib.h cursor.h rtc.h keyboard.h kernel.h \
  terminal.h
i8259.o: i8259.c i8259.h types.h lib.h cursor.h
idt.o: idt.c lib.h types.h cursor.h x86_desc.h idt.h keyboard.h \
  syscalls.h file.h rtc.h syscall_helper.h scheduler.h
kernel.o: kernel.c multiboot.h types.h x86_desc.h lib.h cursor.h i8259.h \
  debug.h tests.h terminal.h keyboard.h rtc.h paging.h kernel.h file.h \
  loader.h syscalls.h scheduler.h
keyboard.o: keyboard.c keyboard.h types.h i8259.h terminal.h lib.h \
  cursor.h
lib.o: lib.c lib.h types.h cursor.h terminal.h
loader.o: loader.c types.h file.h lib.h cursor.h rtc.h keyboard.h \
  kernel.h loader.h
paging.o: paging.c paging.h types.h lib.h cursor.h terminal.h
rtc.o: rtc.c rtc.h types.h i8259.h lib.h cursor.h idt.h
scheduler.o: scheduler.c types.h i8259.h rtc.h lib.h cursor.h terminal.h \
  file.h keyboard.h x86_desc.h schedule_switch.h paging.h syscalls.h
syscall_helper.o: syscall_helper.c lib.h types.h cursor.h file.h rtc.h \
  keyboard.h syscall_helper.h paging.h loader.h x86_desc.h iret_helper.h \
  terminal.h halt.h
syscalls.o: syscalls.c syscalls.h types.h syscall_helper.h file.h lib.h \
  cursor.h rtc.h keyboard.h terminal.h
terminal.o: terminal.c terminal.h types.h keyboard.h syscalls.h paging.h \
  lib.h cursor.h file.h rtc.h i8259.h schedule_switch.h x86_desc.h
tests.o: tests.c tests.h x86_desc.h types.h lib.h cursor.h idt.h rtc.h \
  i8259.h keyboard.h file.h syscall_helper.h terminal.h
tss.o: tss.c x86_desc.h types.h tss.h
